### PR TITLE
Fixing Web URL not being shown and change of icons to text links

### PR DESCRIPTION
**Pull request by VivekRaj2005**
#### References to other Issues or PRs or Relevant literature
Issue #22 and Issue #26 Fix

### CODE REVIEW

**Comment by Kishan-Ved** [comment]
Perfect. Please change the order (in the preview) to this: 
image

Then, we can merge this PR.

**Comment by Kishan-Ved** [comment]
Great! Please resolve the conflicts. Then, we can merge this.

Conflicts occured because PR https://github.com/Kishan-Ved/resume_generator/pull/18 was merged. Please make the necessary changes.

**Comment by VivekRaj2005** [comment]
I have fixed all merge conflicts.

**Comment by Kishan-Ved** [comment]
Amazing. Thanks for this :100:

**Review by Kishan-Ved — APPROVED** [review]

**Comment by VivekRaj2005** [comment]
Thank You

**Comment by Kishan-Ved** [comment]
There are still some conflicts. Please correct them, if you find this difficult, just make a new PR and close this PR.

**Comment by Kishan-Ved** [comment]
style.css has been removed and 2 new .css files have been added. That's the reason for conflicts.

**Pull request closed without merging**
