### PR TITLE
feat: Improved the CSS and HTML of both pages (index.html & resumegen…

### PR DESCRIPTION
**Pull request by JollyJolli**
This PR includes significant design updates to the project:

- **index.html**: 
  - Implemented a complete redesign of the layout and structure.
  - Created a new CSS file for styling, enhancing the overall user interface and experience.

- **Resume Page**:
  - The HTML structure remains unchanged.
  - Renamed the CSS file associated with the resume and applied a new, more formal style to improve its appearance.

#### Changes Made:
- Updated `index.html` with a fresh design.
- Created and linked a new CSS file for `index.html`.
- Renamed the CSS for the resume page and applied a more formal styling.

#### Related Issues:
#17

### CODE REVIEW

**Comment by Kishan-Ved** [comment]
Thanks for this, I'll review it within 24 hours.

**Comment by JollyJolli** [comment]
Thanks

**Comment by Kishan-Ved** [comment]
`resumegenerator.html` looks quite good! Currently, it doesn't fill the full width of the screen, can you please make both the columns broader, so we don't have space wasted on the left and the right?
image
Also, please use the same grey background and black text for headings in the preview (like Academic Details)

**Comment by JollyJolli** [comment]
Hey there of course! Something like this? 
image

**Comment by JollyJolli** [comment]
What do you think about the main page `index.html`? Do you like it?

Also, if you could please add the hacktober labels i would be very greatfull

**Comment by Kishan-Ved** [comment]
> Hey there of course! Something like this? image

Yes, the width seems good. Please use the same grey color for background of the headings, and keep the heading text black. (This is because it should match with the actual latex pdf generated)

I can't see these changes, have you pushed them? You can do it on this PR's branch itself.

**Comment by JollyJolli** [comment]
I have pushed the changes but let me change the colors to be correct

**Comment by JollyJolli** [comment]
Does this seams good for you? 
image

**Comment by Kishan-Ved** [comment]
Width is perfect. Please use the same colors for the heading's background and the text. I have used `style="background-color: lightgray;"` for the background in the current version.
image

Other colors can be adjusted accordingly, but these headings need to be of the same color as in the current version.

**Comment by JollyJolli** [comment]
Ahh! Okey! Sorry, now I got it!

**Comment by JollyJolli** [comment]
Hey there again! Confirm if you like this to push it
image

**Comment by Kishan-Ved** [comment]
Looks good, one final thing: Please make both sides scrollable (independently), as it is on the current website.

**Comment by Kishan-Ved** [comment]
I saw the index.html page, it doesn't seem too responsive, the image is getting cut:
image

If you want, let's do index.html in a separate PR, and keep this PR only for resumegenerator.html. (Remove your changes for index.html)

**Comment by JollyJolli** [comment]
Okey! So i will first make the both side scrollable and in other PR i will make the index responsive

**Comment by JollyJolli** [comment]
hey there! This is ready!

**Comment by JollyJolli** [comment]
Just solved a little issue, i think this is ready!!

**Comment by JollyJolli** [comment]
Please add the `hacktoberfest-accepted` label 🙏🏻

**Review by Kishan-Ved — APPROVED** [review]

**Comment by Kishan-Ved** [comment]
Looks good! Thanks for working on this!

**Comment by Kishan-Ved** [comment]
Please make another PR to enhance index.html. You can completely change the way indes.html file looks. Please make it visually appealing. Just include the text that is currently present.

**Comment by Kishan-Ved** [comment]
I have added the hacktoberfest and hacktoberfest-accepted labels, please check your profile on Hacktoberfest's website and let me know if you can see this PR.

Also, please star this repo, it will increase reach and we will have more contributors :)

**Comment by JollyJolli** [comment]
Perfect, so my next contribution will be with the index.html

**Comment by Kishan-Ved** [comment]
Hi, this is not responsive. On a mobile phone, the right side column is not accessible itself.
image

**Comment by Kishan-Ved** [comment]
I have reverted your changes.  Please make a new PR.

**Pull request merged**
