### PR TITLE
Updated Documentation and Contributor Guidelines

### PR DESCRIPTION
**Pull request by labishbardiya**
Hey @Kishan-Ved,

As per my previous commitment (#50) to enhancing the repository's accessibility and maintainability, I have implemented the following changes:

- **Code Comments** : Added comprehensive comments throughout the codebase to explain the functionality, logic, and purpose of various code blocks.

- **Documentation** : Updated the `README.md` file to:

1. Provide a detailed overview of the project.
2. Add clear **Contributor Guidelines**, including practices for variable naming and commenting conventions.
3. Make the documentation professional, visually appealing, and beginner-friendly.

- **Enhanced Contributor Experience** : Established a structured framework for future contributors to ensure a consistent and efficient collaboration process.

These changes aim to make the repository more accessible and understandable for new and existing contributors while upholding a professional standard.

Please review the changes, and I’m happy to create a **pull request** for you to merge these updates into the repository (Please Check Out). 🎉

Looking forward to your feedback!🤝

### CODE REVIEW

**Comment by Kishan-Ved** [comment]
Thanks for this! I will review it within 24 hours.

**Comment by Kishan-Ved** [comment]
You have not resolved conflicts properly, there are things like this:

image

Please clean the code.

**Comment by Kishan-Ved** [comment]
I think this is because you did `Ctrl C` from a file where conflicts were not resolved and `Ctrl V` in a new file, hence, all these were copied.

**Review by Kishan-Ved — CHANGES_REQUESTED** [review]
Check the comments above

**Comment by labishbardiya** [comment]
Hey @Kishan-Ved, All the conflicts are resolved now, please check it out! Sorry for the unresolved conflicts.

**Comment by Kishan-Ved** [comment]
I have solved some errors. This PR is now ready to be merged.

**Review by Kishan-Ved — APPROVED** [review]

**Pull request merged**
