### PR TITLE
Added Achievements Section

### PR DESCRIPTION
**Pull request by priyamaggarwal18**
Hi this pull request is related to the issue no  #16  

I have added a new section for Achievements in this project, which is also optional, similar to the Skills section. Additionally, I have included vertical space after each achievement to improve the readability of the LaTeX code when compiled on Overleaf.

I really like the idea of generating LaTeX code for Overleaf through HTML forms. When I first saw Overleaf while creating my resume, I found it difficult to understand, so I relied on references and examples; however, this project will surely help simplify the process.

this is the output that I have 

https://github.com/user-attachments/assets/300b79a9-7ee0-4dc6-9135-fa6cd0f2d8cc

### CODE REVIEW

**Comment by Kishan-Ved** [comment]
This is amazing! However, resumes generally have only bullet points (non bold) in the achievements section. Hence, please remove the bold header for every bullet point (do this in overleaf as well as in the preview). Rest is great.

Here's an example of achievements section:
image

Don't worry about the links, just make it have text written in bullet points

**Comment by priyamaggarwal18** [comment]
ok sure I Will work on it.

**Comment by priyamaggarwal18** [comment]
Hi @Kishan-Ved I did the changes you asked for

https://github.com/user-attachments/assets/fa59ce8f-a327-4407-a29d-0b3cd4999d4e

If any other changes required, please do let me know.

**Comment by Kishan-Ved** [comment]
Looks great! Just make the text non bold in the preview (so it matches the actual), and if you can, add bullet points in the preview too. Then, we can merge this PR.

**Review by Kishan-Ved — APPROVED** [review]

**Comment by Kishan-Ved** [comment]
Thanks for this PR! I made very minor changes, to remove the bold text in the preview.

I have merged this PR. Amazing work :100:

**Comment by Kishan-Ved** [comment]
I have added the hacktoberfest and hacktoberfest-accepted labels, please check your profile on Hacktoberfest's website and let me know if you can see this PR.

Also, please star this repo, it will increase reach and we will have more contributors :)

**Comment by priyamaggarwal18** [comment]
Thank you, @Kishan-Ved . I really appreciate your efforts.

**Pull request merged**
