### PR TITLE
Enhancement: Added IITGN Logo, Updated Font, and Modified Background in Resume Generator

### LINKED ISSUE #49: Enhancement: Add IITGN Logo, Update Font, and Modify Background in Resume Generator
This issue covers the enhancement of the **Resume Generator** to improve its design and appearance. Below are the changes:

### IITGN Logo Addition:

Added the IITGN (Indian Institute of Technology Gandhinagar) logo to the `Images` folder.
Integrated the logo beside the text "Indian Institute of Technology Gandhinagar" in the `resumegenerator.html` file.

### Font Update:

Updated the font-family to "Arial, Helvetica, sans-serif" across the `resumegenerator.html` file for a cleaner and more professional look.

### Background Modification:

Lightened the background color of the `resumegenerator.html` file to make the content more visually appealing and readable.

### Expected Impact:

- Brand Alignment: The IITGN logo provides a visual representation of the institution, increasing recognition.
- Enhanced Aesthetics: A cleaner, modern font combined with a lighter background creates a more professional and engaging design.

Kindly review the proposed changes and provide feedback or approval to proceed with the implementation.

### PR DESCRIPTION
**Pull request by labishbardiya**
Fixes #49

### Brief Description of What is Fixed or Changed

1. Added IITGN Logo:

Placed the **IITGN (Indian Institute of Technology Gandhinagar)** logo in the `Images` folder.
Incorporated the logo beside the text "Indian Institute of Technology Gandhinagar" in the `resumegenerator.html` file.

2. Updated Font:

Changed the font-family throughout the `resumegenerator.html` file to "**Arial, Helvetica, sans-serif**" for a more refined and professional look.

3. Modified Background:

Lightened the background color of the `resumegenerator.html` file to improve readability and the overall aesthetics of the page.

### Example for Project

Screenshot 2024-10-10 130038

### Other comments

These changes aim to enhance the visual appeal and branding of the Resume Generator by aligning it with the IITGN identity while improving user experience through better font readability and a lighter, more user-friendly background.

### CODE REVIEW

**Comment by Kishan-Ved** [comment]
This PR looks good. Just remove the IITGN Logo. We can keep other changes. Thanks!

**Comment by labishbardiya** [comment]
@Kishan-Ved, Removed the IITGN Logo.

And, by the way, my IITGN Roll No. is `24120011`

**Comment by Kishan-Ved** [comment]
This looks good, thanks!

**Review by Kishan-Ved — APPROVED** [review]

**Comment by Kishan-Ved** [comment]
I have added the hacktoberfest and hacktoberfest-accepted labels, please check your profile on Hacktoberfest's website and let me know if you can see this PR.

Also, please star this repo, it will increase reach and we will have more contributors :)

**Comment by labishbardiya** [comment]
Thank you, this PR is visible on the Hacktoberfest's website. Starred 🌟

**Comment by labishbardiya** [comment]
Hey @Kishan-Ved, I would like to seek your approval for creating a separate pull request. In this new pull request, I intend to add **comments** and **documentation** throughout the codebase and update the **`README`** file. The goal is to establish clear guidelines for future contributors, ensuring that code documentation and commenting practices are followed. This will make the repository more accessible and easier to understand for anyone who wants to contribute in the future. I can work on this if you agree.

**Comment by Kishan-Ved** [comment]
Yes, please work on this. Additionally, you can format the code (correct indentations etc.) while adding comments.

Make a new PR.

**Comment by labishbardiya** [comment]
Sure.

**Pull request merged**
